import { tool } from '@openai/agents';
import { z } from 'zod';

export const UPDATE_FLIGHT_SUGGESTED_QUESTIONS_TOOL_NAME =
  'update_flight_suggested_questions';

const updateFlightSuggestedQuestionsSchema = z.object({
  suggestedQuestions: z
    .array(z.string().min(1))
    .min(3)
    .max(5)
    .describe(
      'The final user-perspective suggested questions generated by the Flight Agent. The tool stores these exact strings without rewriting them.',
    ),
});

export function updateFlightSuggestedQuestions({
  currentFlightContext,
  suggestedQuestions,
} = {}) {
  const context = currentFlightContext || {};

  if (!Array.isArray(suggestedQuestions)) {
    return {
      ok: false,
      code: 'INVALID_SUGGESTED_QUESTIONS',
      message: 'suggestedQuestions must be an array of strings.',
    };
  }

  if (
    suggestedQuestions.length < 3 ||
    suggestedQuestions.length > 5 ||
    suggestedQuestions.some((question) => typeof question !== 'string' || question.length === 0)
  ) {
    return {
      ok: false,
      code: 'INVALID_SUGGESTED_QUESTIONS',
      message: 'suggestedQuestions must contain 3 to 5 non-empty strings.',
    };
  }

  context.flight = context.flight && typeof context.flight === 'object' ? context.flight : {};
  context.flight.suggestedQuestions = suggestedQuestions;

  return {
    ok: true,
    suggestedQuestions,
  };
}

export const UpdateFlightSuggestedQuestionsTool = tool({
  name: UPDATE_FLIGHT_SUGGESTED_QUESTIONS_TOOL_NAME,
  description:
    'Persist Flight Agent generated suggested questions into context.flight.suggestedQuestions. This tool does not generate, rank, infer, rewrite, or filter suggestions. It only stores the provided strings and returns success.',
  parameters: updateFlightSuggestedQuestionsSchema,
  strict: true,
  execute(input, runContext) {
    const appContext = runContext?.context || {};
    const output = updateFlightSuggestedQuestions({
      currentFlightContext: appContext,
      suggestedQuestions: input.suggestedQuestions,
    });

    appContext.toolCallLog ||= [];
    appContext.toolCallLog.push({
      tool: UPDATE_FLIGHT_SUGGESTED_QUESTIONS_TOOL_NAME,
      searchKey: appContext.searchKey || appContext.sid || null,
      input,
      suggestedQuestions: output.suggestedQuestions || [],
      ok: output.ok,
      code: output.code || null,
    });

    return output;
  },
});

export function update_flight_suggested_questions(input) {
  return updateFlightSuggestedQuestions(input);
}
